/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppShellRouteImport } from './routes/_authenticated/_app-shell'
import { Route as AuthenticatedMovieIdRouteImport } from './routes/_authenticated/movie.$id'
import { Route as AuthenticatedAppShellWatchlistRouteImport } from './routes/_authenticated/_app-shell/watchlist'
import { Route as AuthenticatedAppShellDiscoveryRouteImport } from './routes/_authenticated/_app-shell/discovery'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppShellRoute = AuthenticatedAppShellRouteImport.update({
  id: '/_app-shell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMovieIdRoute = AuthenticatedMovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppShellWatchlistRoute =
  AuthenticatedAppShellWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AuthenticatedAppShellRoute,
  } as any)
const AuthenticatedAppShellDiscoveryRoute =
  AuthenticatedAppShellDiscoveryRouteImport.update({
    id: '/discovery',
    path: '/discovery',
    getParentRoute: () => AuthenticatedAppShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/discovery': typeof AuthenticatedAppShellDiscoveryRoute
  '/watchlist': typeof AuthenticatedAppShellWatchlistRoute
  '/movie/$id': typeof AuthenticatedMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/discovery': typeof AuthenticatedAppShellDiscoveryRoute
  '/watchlist': typeof AuthenticatedAppShellWatchlistRoute
  '/movie/$id': typeof AuthenticatedMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/_authenticated/_app-shell': typeof AuthenticatedAppShellRouteWithChildren
  '/_authenticated/_app-shell/discovery': typeof AuthenticatedAppShellDiscoveryRoute
  '/_authenticated/_app-shell/watchlist': typeof AuthenticatedAppShellWatchlistRoute
  '/_authenticated/movie/$id': typeof AuthenticatedMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design-system' | '/discovery' | '/watchlist' | '/movie/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design-system' | '/discovery' | '/watchlist' | '/movie/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/design-system'
    | '/_authenticated/_app-shell'
    | '/_authenticated/_app-shell/discovery'
    | '/_authenticated/_app-shell/watchlist'
    | '/_authenticated/movie/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app-shell': {
      id: '/_authenticated/_app-shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movie/$id': {
      id: '/_authenticated/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof AuthenticatedMovieIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app-shell/watchlist': {
      id: '/_authenticated/_app-shell/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedAppShellWatchlistRouteImport
      parentRoute: typeof AuthenticatedAppShellRoute
    }
    '/_authenticated/_app-shell/discovery': {
      id: '/_authenticated/_app-shell/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedAppShellDiscoveryRouteImport
      parentRoute: typeof AuthenticatedAppShellRoute
    }
  }
}

interface AuthenticatedAppShellRouteChildren {
  AuthenticatedAppShellDiscoveryRoute: typeof AuthenticatedAppShellDiscoveryRoute
  AuthenticatedAppShellWatchlistRoute: typeof AuthenticatedAppShellWatchlistRoute
}

const AuthenticatedAppShellRouteChildren: AuthenticatedAppShellRouteChildren = {
  AuthenticatedAppShellDiscoveryRoute: AuthenticatedAppShellDiscoveryRoute,
  AuthenticatedAppShellWatchlistRoute: AuthenticatedAppShellWatchlistRoute,
}

const AuthenticatedAppShellRouteWithChildren =
  AuthenticatedAppShellRoute._addFileChildren(
    AuthenticatedAppShellRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppShellRoute: typeof AuthenticatedAppShellRouteWithChildren
  AuthenticatedMovieIdRoute: typeof AuthenticatedMovieIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppShellRoute: AuthenticatedAppShellRouteWithChildren,
  AuthenticatedMovieIdRoute: AuthenticatedMovieIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
